import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import { AuthProvider } from './../components/Contexts/AuthContext';
import { CartProvider } from '@/components/Contexts/CartContext';
import { Toaster } from '@/components/ui/toaster';
import Provider from './../components/Provider/Provider';
const inter = Inter({ subsets: ['latin'] })



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <AuthProvider>
            <CartProvider>
              {children}
              <Toaster />
            </CartProvider>
          </AuthProvider>
        </Provider>
      </body>
    </html>
  )
}
